APIFY_API_TOKEN="apify_api_Xl86JAYsbLofNZMthjSs2frGrUcDAt2VfO1r"

[accounts]
instagram = ["wifeygpt", "yeti_is_my_new_marketing", "walk_for_wifeygpt", "wifeygpt_memes", "humans_vs_ai_", "alien_ai_vlogs", "hannah_on_wifeygpt", "mia_wifeygpt", "disha_ai_girl", "leila_wifeygpt", "brianna_wifeygpt", "ella_wifeygpt", "lisa_wifeygpt", "sophia_wifeygpt", "rosawifeygpt", "smash.or.pass_ai"]
tiktok = ["yeti_is_my_new_marketing", "ai_girlfriends_wifeygpt", "walk_for_wifeygpt", "wifeygpt_memes", "humans_vs_ai_", "alien_ai_vlogs", "hannah_on_wifeygpt", "mia_wifeygpt", "disha_ai_girl", "leila_wifeygpt", "brianna_wifeygpt", "ella_wifeygpt", "lisa_wifeygpt", "sophia_wifeygpt", "smash.or.pass_ai"]

[accounts.settings]
instagram_posts_limit = 200
tiktok_videos_limit = 100
